# Generated by Django 5.2 on 2025-05-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plug_reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('current_power', models.FloatField()),
                ('today_runtime', models.IntegerField()),
                ('today_energy', models.FloatField()),
                ('month_runtime', models.IntegerField()),
                ('month_energy', models.FloatField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('energy_wh', models.FloatField()),
            ],
        ),
    ]
