# Generated by Django 5.2 on 2025-05-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plug_reading',
            options={'managed': False},
        ),
    ]
