# Generated by Django 5.2 on 2025-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_plug_reading_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='plug_reading_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('current_power', models.FloatField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('energy_wh', models.FloatField()),
            ],
            options={
                'db_table': 'plug_readings',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='plug_reading',
            table='plug_readings',
        ),
    ]
