# Generated by Django 5.2 on 2025-05-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_plug_reading_chart_alter_plug_reading_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='plug_reading_chart',
        ),
    ]
